language: cpp

os : linux
sudo: required

compiler:
  - gcc
  - clang

jdk:
  - openjdk8
  - oraclejdk8

matrix:
  include:
    - python: "3.4"
      env: TEST_SUITE=pythontests34
    - python: "3.5"
      env: TEST_SUITE=pythontests35
    - java: oraclejdk8
      env: TEST_SUITE=javatestsoracle BUILD_ARGS="-DJAVA=ON"
    - java: openjdk8
      env: TEST_SUITE=javatestsopen BUILD_ARGS="-DJAVA=ON"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y --force-yes cmake libgmp-dev zlib1g-dev

install:
  - cmake ${BUILD_ARGS} .
  - make
  - sudo make install

script:
  - cd src/monosat/api/python/
  - sudo python setup.py install -f
  - cd ../../../../
  - echo "${TEST_SUITE}"



