language: cpp

branches:
  only:
    - master
    - dev
    - travis # specifically for experimenting with travis builds
    - coverity_scan

os :
  - linux
  - osx

sudo: required

compiler:
  - gcc
  - clang

jdk:
  - openjdk8
  - oraclejdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "bgRuJoOg1TUfdnIBq8ahqr38r0qmebX/LCVLmQ10wKjFMs/G4odF1dcdBzhkMdzGB2jE+uAhNkm72PlJv4s2Bkqn/BjRMdzyb9LHMSg1Vfyeyq7PTVUIM3J5ArGbIZ2De24uNvBMamFj9dzdqpPeVUTdcceaI2TfO7NOeCZ3DPyO6AOIDjCjESWTG5ghFuFd3h4c+6ihB+UJt03oM0U2s/lzv7QdRYsTPAi1arn3pAnag8HvK9fN6/JsH3NP5l49WGGwu8H5bCZQaGkxmDiKoY52VTE6H64vKu6P1chgSNpHAj4CIhwUn8D1egankanz2ukuENMliNXyabznOl+T15cj4FB+A6pl7mgTAzJO+MiQprrYtjSH5W1Lug7Cz0IB+oshsu1SoO4N7odqhKsQznXGivOpVy5BG/MdjeR0ICG/WYLWDHZSQRtlLyxUtJsm3+eXv6g9KtAT5Hdx8OIMHT3yLQy1pBr14wLqXjdjp4ySnsJcBRd8/ZEff6fc5+dp4AiR3TppzLNQ/8/YBk+tfWnYcE0ehXKWxm3sTr2kl3k0oKz7UyYtk58ERfppy/qWcGVeLHcjHhmfNOEhFUAw3Awlzz+kpsyk4VvTIR6UysQhSICUCw8LeqTDMcSjDzHFiGd3Wqn1Xd+mzHKGuczeWaI9xpBPdoLTpL7OseyqAjo="

matrix:
  include:
    - java: openjdk8
      python: "3.4"
      env: TEST_PYTHON=1 BUILD_TARGET="libmonosat" JDK_VERSION="openjdk8" PYTHON_VERSION="python3.4" BUILD_ARGS="-DPYTHON=ON"
      addons:
        coverity_scan:
          project:
            name: "sambayless/monosat"
            description: "MonoSAT constraint solver"
          notification_email: sambayless@gmail.com
          build_command_prepend: "cmake -DPYTHON=OFF -DJAVA=OFF"
          build_command: "make"
          branch_pattern: coverity_scan
      if: branch = coverity_scan
      before_script: echo "Coverity Scan"
    - java: openjdk8
      python: "3.4"
      env: TEST_PYTHON=1 BUILD_TARGET="libmonosat" JDK_VERSION="openjdk8" PYTHON_VERSION="python3.4"  BUILD_ARGS="-DPYTHON=ON -DCYTHON=ON"
    - java: oraclejdk8
      env: TEST_PYTHON=1 TEST_JAVA=1 BUILD_TARGET="libmonosat" BUILD_ARGS="-DPYTHON=ON -DJAVA=ON" JDK_VERSION="oraclejdk8" PYTHON_VERSION="python3.4"
      python: "3.4"
    - java: openjdk9
      python: "3.4"
      env: TEST_PYTHON=1 TEST_JAVA=1 BUILD_TARGET="libmonosat" BUILD_ARGS="-DPYTHON=ON -DJAVA=ON -DGPL=OFF" JDK_VERSION="openjdk9" PYTHON_VERSION="python3.4"
      os: linux
      dist: trusty
      compiler: clang
    - java: openjdk9
      python: "3.6"
      os: osx
      compiler: clang
      env: TEST_PYTHON=1 TEST_JAVA=1 BUILD_TARGET="libmonosat" BUILD_ARGS="-DPYTHON=ON -DJAVA=ON -DGPL=OFF" JDK_VERSION="openjdk9" PYTHON_VERSION="python3.6"
  allow_failures:
    - java: openjdk8
      python: "3.4"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - TEST_PYTHON=1 TEST_JAVA=1 BUILD_TARGET="libmonosat" BUILD_ARGS="-DJAVA=ON" MATRIX_EVAL="CC=gcc-5 && CXX=g++-5" JDK_VERSION="oraclejdk9" PYTHON_VERSION="python3.4"

    - java: openjdk8
      python: "3.4"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - TEST_PYTHON=1 TEST_JAVA=1 BUILD_ARGS="-DJAVA=ON -DGPL=OFF" MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" JDK_VERSION="openjdk8" PYTHON_VERSION="python3.4"

before_install:
  - echo "os is ${TRAVIS_OS_NAME}"
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew update; brew install python3 || brew outdated python3 || brew upgrade python3 || true ; fi
  # see https://github.com/travis-ci/travis-ci/issues/8581
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157 || sudo apt-get -qq update; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get install -y --force-yes cmake libgmp-dev zlib1g-dev; fi
  - eval "${MATRIX_EVAL}"
  - echo "Selected Java ${JDK_VERSION}"  || true
  - jdk_switcher use ${JDK_VERSION}  || true
  - java -version  || true
  - echo "Selected Python ${PYTHON_VERSION}"
  - python3 --version || true
  - if [[ "${TRAVIS_BRANCH}" == "coverity_scan" ]]; then echo -n | openssl s_client -connect "https://scan.coverity.com:443" | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca- ; fi

install:
  - cmake ${BUILD_ARGS} .
  - make ${BUILD_TARGET}
  - sudo make install

script:
 - ROOT=$PWD
 - if [[ "$TEST_PYTHON" -eq "1" ]]; then echo "Running python tests" && cd ${ROOT}/src/monosat/api/python/ && python3 -m unittest discover && echo "Completed python tests"; fi
 - if [[ "$TEST_JAVA" -eq "1" ]]; then echo "Running java tests" &&  cd ${ROOT}/src/monosat/api/java/tests && javac -cp ".:${ROOT}/monosat.jar:junit-4.12.jar:hamcrest-core-1.3.jar" monosat/*.java && java -Djava.library.path=${ROOT} -cp ".:${ROOT}/monosat.jar:junit-4.12.jar:hamcrest-core-1.3.jar" org.junit.runner.JUnitCore  monosat.TestSuite && echo "Completed java tests"; fi

