language: cpp

os :
  - linux
  - osx

sudo: required

compiler:
  - gcc
  - clang

jdk:
  - openjdk8
  - oraclejdk8

matrix:
  include:
    - python: "3.3"
      env: TEST_PYTHON=1
    - java: oraclejdk8
      env: TEST_PYTHON=1 TEST_JAVA=1 BUILD_ARGS="-DJAVA=ON"
      python: "3.4"
    - java: openjdk8
      python: "3.5"
      env: TEST_PYTHON=1 TEST_JAVA=1 BUILD_ARGS="-DJAVA=ON"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - java: openjdk8
      python: "3.6"
      env: TEST_PYTHON=1 TEST_JAVA=1 BUILD_ARGS="-DJAVA=ON -DGPL=OFF"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - java: openjdk9
      python: "3.6"
      env: TEST_PYTHON=1 TEST_JAVA=1 BUILD_ARGS="-DJAVA=ON -DGPL=OFF"
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - java: openjdk9
      python: "3.6"
      os: osx
      # python doesn't seem to be installing correctly in travis on osx.
      env: TEST_PYTHON=0 TEST_JAVA=1 BUILD_ARGS="-DJAVA=ON -DGPL=OFF"

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew outdated python3 || brew upgrade python3 ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get install -y --force-yes cmake libgmp-dev zlib1g-dev; fi

install:
  - cmake ${BUILD_ARGS} .
  - make
  - sudo make install


script:
 - ROOT=$PWD
 - echo ${TRAVIS_JDK_VERSION}
 - jdk_switcher use ${TRAVIS_JDK_VERSION}  || true # suppress errors on this line
 - python3 --version || true # suppress errors on this line
 - java -version  || true # suppress errors on this line
 - if [[ -n "$TEST_PYTHON" ]]; then cd ${ROOT}/src/monosat/api/python/ && sudo python3 setup.py -q install && python3 -m unittest discover; fi
 - if [[ -n "$TEST_JAVA" ]]; then cd ${ROOT}/src/monosat/api/java/tests && javac -cp ".:${ROOT}/monosat.jar:junit-4.12.jar:hamcrest-core-1.3.jar" monosat/*.java && java -Djava.library.path=${ROOT} -cp ".:${ROOT}/monosat.jar:junit-4.12.jar:hamcrest-core-1.3.jar" org.junit.runner.JUnitCore  monosat.TestSuite; fi


