language: cpp

os : linux

compiler:
  - gcc
  - clang

sudo: required

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get install -y --force-yes cmake libgmp-dev zlib1g-dev

script:
  - cmake .
  - make
  - sudo make install

