language: cpp

os : linux
sudo: required

compiler:
  - gcc
  - clang

jdk:
  - openjdk8
  - oraclejdk8

matrix:
  include:
    - python: "3.4"
      env: TEST_PYTHON=1
    - python: "3.5"
      env: TEST_PYTHON=1
    - python: "3.6"
      env: TEST_PYTHON=1
    - java: oraclejdk8
      env: TEST_PYTHON=1 TEST_JAVA=1 BUILD_ARGS="-DJAVA=ON"
    - java: openjdk8
      env: TEST_PYTHON=1 TEST_JAVA=1 BUILD_ARGS="-DJAVA=ON"
    - java: openjdk8
      env: TEST_PYTHON=1 TEST_JAVA=1 BUILD_ARGS="-DJAVA=ON -DGPL=OFF"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y --force-yes cmake libgmp-dev zlib1g-dev junit4

install:
  - cmake ${BUILD_ARGS} .
  - make
  - sudo make install


script:
 - ROOT=$PWD
 - if [[ -n "$TEST_PYTHON" ]]; then cd ${ROOT}/src/monosat/api/python/ && sudo python3 setup.py install && python3 -m unittest discover; fi
 - if [[ -n "$TEST_JAVA" ]]; then cd ${ROOT}/src/monosat/api/java/tests && javac -cp ".:../../../../../monosat.jar:/usr/share/java/junit4.jar" monosat/*.java && java -Djava.library.path=../../../../../ -cp ".:../../../../../monosat.jar:/usr/share/java/junit4.jar" org.junit.runner.JUnitCore  monosat.TestSuite; fi


