language: cpp

os :
  - linux
  - osx

sudo: required

compiler:
  - gcc
  - clang

jdk:
  - openjdk8
  - oraclejdk8

matrix:
  include:
    - python: "3.4"
      env: TEST_PYTHON=1
    - python: "3.5"
      env: TEST_PYTHON=1
    - python: "3.6"
      env: TEST_PYTHON=1
    - java: oraclejdk8
      env: TEST_PYTHON=1 TEST_JAVA=1 BUILD_ARGS="-DJAVA=ON"
    - java: openjdk8
      env: TEST_PYTHON=1 TEST_JAVA=1 BUILD_ARGS="-DJAVA=ON"
    - java: openjdk8
      env: TEST_PYTHON=1 TEST_JAVA=1 BUILD_ARGS="-DJAVA=ON -DGPL=OFF"
    - java: openjdk9
      env: TEST_PYTHON=1 TEST_JAVA=1 BUILD_ARGS="-DJAVA=ON -DGPL=OFF"
    - java: openjdk9
      python: 3.6
      os: osx
      env: TEST_PYTHON=1 TEST_JAVA=1 BUILD_ARGS="-DJAVA=ON -DGPL=OFF"
before_install:
  #- if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew install -f gmp zlib ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get install -y --force-yes cmake libgmp-dev zlib1g-dev; fi

install:
  - cmake ${BUILD_ARGS} .
  - make
  - sudo make install


script:
 - ROOT=$PWD
 - if [[ -n "$TEST_PYTHON" ]]; then cd ${ROOT}/src/monosat/api/python/ && sudo python3 setup.py install && python3 -m unittest discover; fi
 - if [[ -n "$TEST_JAVA" ]]; then cd ${ROOT}/src/monosat/api/java/tests && JUNIT_PATH="junit-4.12.jar:hamcrest-core-1.3.jar " && javac -cp ".:../../../../../monosat.jar:${JUNIT_PATH}" monosat/*.java && java -Djava.library.path=../../../../../ -cp ".:../../../../../monosat.jar:${JUNIT_PATH}" org.junit.runner.JUnitCore  monosat.TestSuite; fi


